version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - task gen:completions
    - task gen:manpage

builds:
  - id: storm
    main: ./cmd
    binary: storm
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, "386"]

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    # 👇 this is the important part
    files:
      - completions/**
      - manpages/**
    # the `**` ensures recursive inclusion from project root

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    ---
    Made by [Owais](https://github.com/desertthunder/desertthunder).

homebrew_casks:
  - name: storm
    repository:
      owner: stormlightlabs
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/stormlightlabs/git-storm"
    description: "A changelog manager with TUIs for review and release"
    license: MIT
    url:
      template: "https://github.com/stormlightlabs/git-storm/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/stormlightlabs/git-storm/"
    binaries:
      - storm
    manpages:
      - manpages/storm.1
    completions:
      bash: completions/storm.bash
      zsh: completions/storm.zsh
      fish: completions/storm.fish
    directory: Casks
    commit_msg_template: "Brew cask update for Storm version {{ .Tag }}"
    skip_upload: false
    ids:
      - default
